### PR TITLE
Added getExternalFilesDirs support.

### PR DESCRIPTION
**Pull request by totalretribution**
I have added support for getExternalFilesDirs.

### CODE REVIEW

**Comment by pylerSM** [comment]
Maybe we should.even look if oldDirPaths array does not contain our new path since official API can return paths to internal and sd cards. So it would be a duplication and it may crash some apps.

**Comment by totalretribution** [comment]
Actually you have reminded me of an bug I had on the weekend with my personal plex version in that when plex called getExternalFilesDirs, getExternalFilesDir was also called. I will have to check this as it may make supporting getExternalFilesDirs pointless for anything other than very niche situations.

**Comment by pylerSM** [comment]
Okey,do tests and then inform me. Thanks

**Comment by totalretribution** [comment]
I have added a check for Null and I checked and getExternalFilesDir is not called by getExternalFilesDirs. This also checks that CustomInternalSD is not blank.

**Comment by pylerSM** [comment]
Good. I will merge this and do small changes to fit my code style :)

**Pull request merged**
