### PR TITLE
Fixed  "Full Access to External SDcard"

### PR DESCRIPTION
**Pull request by kishorerprem**
Fixed  "Full Access to External SDcard" for Marshmallow/CM13.

### CODE REVIEW

**Comment by pylerSM** [comment]
Can you check this? https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/PermissionGranter.java

Cant be the whole code simplified? :)

**Comment by kishorerprem** [comment]
The "grantPermissionsLPw" hook may can be simplified. But, orher hooks can't be simplified. "writePermissionsLPr" & "writePackageLPr" hook is to avoid writing the granted permissions in packages.xml. These two hooks are help to restore the permissionstate to default, when we deactivating the module or the option "Full Access to External SD". I think current code is better to get good result from this option.

**Comment by pylerSM** [comment]
I am in favour of simplier code :) I dont think that writing that permission to xml file is a big deal imho. I pushed simplier code and we will see.

**Comment by kishorerprem** [comment]
You are right. Your code is great.

**Comment by kishorerprem** [comment]
After second reboot the option "Full Access to External SD" will be useless. This is the result of your simplified code. After second reboot I have deactivated the option in your module & rebooted. But, its still allowing me to write external storage. This happend cause of removing another two hooks. During first boot the Permission "WRITE_MEDIA_STORAGE" is granted for every apps & during second boot its written to packages.xml permanently as installed permission for every apps. So, still my code is better to get perfection of this option. You won't get best result by simplifying any code in any situation. Good luck. 😀

**Comment by pylerSM** [comment]
I know. But anyway modue with this functionaly off is useless. We need that permission. If it stays for apps after module uninstallation, I dont think it can cause something bad at all.

**Comment by kishorerprem** [comment]
Then I have a idea to be more simplier,  you should remove the checkbox from your module. I don't think the ckeckbox is necessary for this option.

**Comment by pylerSM** [comment]
But I dont want to confuse users. I keep it :)

**Pull request merged**
